---
title: "Lab 7"
author: "Lauren, Ryan, Chris, Katie"
date: "3/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Who is hiring you?

We have been hired by the Census Bureau to look at trends of mortality.

## Overall Question

Does a relationship exist between race (White, Black, Hispanic, Other) and leading causes of death? Futhermore, are these trends consistent across states?
This question proves relevant as an exploration into if race can indicate liklihood of causes of death. For example, people think that race can act as clue to individuals risk of heart disease. Perhaps we will identify a relationship with heart disease and race within this dataset to support that claim. It is interesting to add the state component because each state has unique conditions that may impact other mortality factors.



## Description of the Dataset

We have decided on a very large data set. We are focusing on the "Leading Causes of Death" tab. This data frame has aboout 230 attributes and over 3000 observations. The attributes include county, state, and causes of death ranging from birth defect to injury to cancer. 
We plan to tidy the data set by removing redundant or unnecessary attributes and reorganizing the data to end with 5 or fewer attributes. 

## Individual Questions

### Lauren

I am interested in comparing the leading causes of death in Illinois versus Colorado. Being from Illinois, and now living in Colorado, I recognize how different the lifestyles are in each state. Even just what people buy at the grocery stores tells me that Colorado is a much healthier state than Illinois. I want to see if this intuition is reflected in leading causes of death. For example, I would expect to find more outdoor accidents leading to death in Colorado because it is a much more active state than Illinois. This becomes interesting on a larger scale because Colorado is known as one of the least-obese states and has the most physcial activity. Considering leading causes of deaths in the healthiest state could result in some more insights into the definition of "healthy". 

### Ryan
A question I have regarding this data set is: "Is there a significant difference in causes of death in northern states versus southern states?" This question is important because it could give direct insight on whether or not where you live in the United States has any effect on death rates. This insight could be used to analyze the effect of weather, culture, ect. on the causes of death. 


### Chris

the most attractive important variable that I want to discuss is the "cancer" and "homicide" especially the baby's cancer rate and the baby's homicide, cause we all know that the baby's grow up is a big problem in our society and we all hope that we could improve that stituation and avoid the death rate relate to baby. for that I was concern that tidy 5 or 6 state, I just try to find the most population state like "CA", "IL" some states like that. If I could find a way to analysis the baby's death, I could make some conclusion and make some recommand step. It might help our soceity.



### Katie

## Visualization from 2-28 Team Application Exercise
